export const MAXIMUM_ANNUAL_SUPER_CONTRIBUTIONS = 27_500;

export const FHSS_MAX_ANNUAL_DEPOSIT = 15_000;
export const FHSS_MAX_TOTAL_DEPOSIT = 50_000;

export const SGC_RATE = 0.105;

export const LEVY_SINGLE_EXEMPTION_THRESHOLD = 23_226;
export const LEVY_SINGLE_REDUCTION_THRESHOLD = 29_033;
export const LEVY_FAMILY_EXEMPTION_THRESHOLD = 39_167;
export const LEVY_FAMILY_REDUCTION_THRESHOLD = 48_958;
