export const MIN_EMPLOYER_SUPER_RATE = 0.1;

export const LEVY_SINGLE_EXEMPTION_THRESHOLD = 23_226;
export const LEVY_SINGLE_REDUCTION_THRESHOLD = 29_033;
export const LEVY_FAMILY_EXEMPTION_THRESHOLD = 39_167;
export const LEVY_FAMILY_REDUCTION_THRESHOLD = 48_958;
